### ISSUE TITLE
Question about replicate WaNet attack result?

### ISSUE THREAD

**Issue by CuriousCatCoder** [rkteddy/channel-Lipschitzness-based-pruning#2]
Dear authors,

Congratulations on your great work. I have a question about how to replicate the results of WaNet attack.

I tried to use the [official code of WaNet ](https://github.com/VinAIResearch/Warping-based_Backdoor_Attack-release) with their [official checkpoints](https://public.vinai.io/checkpoints_revised.zip) `"cifar10_all2one_morph.pth"`

```
With no defense, the result is 94.15% (ACC), and 99.50 (ASR).
With CLP defense, the result is 53.50% (ACC), and 93.96 (ASR).
```

I set the threshold value u=3, as suggested in your paper. But the result is not as good. Can you help me?

**Comment by rkteddy** [comment]
Thanks for your interest.
We didn't use the original checkpoint, since they used PreActResNet as the backbone, while we used ResNet.
I checked the performance of the CLP on the official checkpoint and found that the poor performance was due to the architecture not matching the assumption in our code, which is that each convolution module should be followed by a BN module. Unfortunately, it seems difficult to write a universal check to verify which module comes after the other, as they may not be used in the same sequence as they are presented in model.modules(). Therefore, it is better to write an architecture-specific code to make sure the correct implementation is applied if you decide to change the architecture. We have provided another version that works with PreActResNet-18, but we cannot guarantee that it will work with other architectures:

```
def CLP(net, u):
    params = net.state_dict()
    conv = None
    for name, m in net.named_modules():
        if isinstance(m, nn.BatchNorm2d) and isinstance(conv, nn.Conv2d):
            std = m.running_var.sqrt()
            weight = m.weight

            channel_lips = []
            for idx in range(weight.shape[0]):
                # Combining weights of convolutions and BN
                w = conv.weight[idx].reshape(conv.weight.shape[1], -1) * (weight[idx]/std[idx]).abs()
                channel_lips.append(torch.svd(w.cpu())[1].max())
            channel_lips = torch.Tensor(channel_lips)

            index = torch.where(channel_lips>channel_lips.mean() + u*channel_lips.std())[0]

            params[name+'.weight'][index] = 0
            params[name+'.bias'][index] = 0
            print(index)

        # Convolutional layer should be followed by a BN layer by default
        else:
          conv = m

    net.load_state_dict(params)
```

And here's our results:
|     | Original | u=3.0   |  u=2.8 |  u=2.6 |  u=2.4 |  u=2.2 |  u=2.0 |
|-----|----------|-------|--------|--------|--------|--------|--------|
| ACC | 94.08    | 93.97 | 93.87  | 93.81  | 93.79  | 93.64  | 93.34  |
| ASR | 99.50    | 91.90 | 91.79  | 90.17  | 8.37   | 9.62   | 4.41   |

**Comment by CuriousCatCoder** [comment]
Thank you for such a detailed explanation. I updated the code for PreActResNet and was able to get much better results. This is the result after applying CLP defense to WaNet model (PreAct ResNet18, CIFAR-10, All2One), and using WaNet eval.py :
Original | u=3.0 | u=2.8 | u=2.6 | u=2.4 | u=2.2 | u=2.0
-- | -- | -- | -- | -- | -- | --
ACC | 94.15 | 93.77 | 93.66 | 93.74 | 93.58 | 93.26
ASR | 99.50 | 92.56 | 91.09 | 16.97 | 18.06 | 13.14

However, there is still a large variation in the ASR. May I ask which did you use the official checkpoint? And did you use WaNet eval.py or your own test.py? I'm not sure where the difference come from.

**Comment by rkteddy** [comment]
I use the checkpoint from the official repository.
The official code does not filter out samples from the target class when evaluating the model's performance under attack, resulting in a different ASR than ours. If you filter these out, you may achieve similar results to ours.

**Comment by CuriousCatCoder** [comment]
Thank you for your respond.
